
name: Continuos Deployment workflow

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Git config
        run: |
          git config --global user.email "jreycid@gmail.com"
          git config --global user.name "jreycid"
      - name: Install
      #  run: ci
      #- name: Build
      #  run: run build
      #- name: Deploy
      #  run: npm run deploy -- -r git@github.com:jreycid/Tutorial-GIT.git
        run: run deploy -- -r git@github.com:jreycid/Tutorial-GIT.git
